[bot]
token  = ""
admins = []
params = {}

[image]
sample = "info.html"
select = "#container"

[process]
signals = [
	"SIGHUP",  "SIGINT",    "SIGQUIT", "SIGILL",
	"SIGTRAP", "SIGABRT",   "SIGBUS",  "SIGFPE",
	"SIGKILL", "SIGUSR1",   "SIGSEGV", "SIGUSR2",
	"SIGPIPE", "SIGALRM",   "SIGTERM", "SIGSTKFLT",
	"SIGCHLD", "SIGCONT",   "SIGSTOP", "SIGTSTP",
	"SIGTTIN", "SIGTTOU",   "SIGURG",  "SIGXCPU",
	"SIGXFSZ", "SIGVTALRM", "SIGPROF", "SIGWINCH",
	"SIGPOLL", "SIGPWR",    "SIGSYS"
]
